languageCode: en-us
params:
  sectionList:
    articleSnippetStyle: listStyle
  onesignalSDKID: c297670d-63a2-4232-8f52-a8602fdffc33
  copyright:
    start: 2021
    today: 2023
    rightholder: dplayz Games
    notes: Elements of this website are owned by dplayz Games unless otherwise noted.
    managedByWhom: Managed by dplayz Games
  cms:
    backend:
      name: github
      github:
        repo: dplayz/web
        branch: main
        useGraphQL: false
        auth_endpoint: /api/auth
    media_folder: images
    public_folder: static/images
    logo_url: null
    collections:
      - folder: readFile/info
        create: true
        fieldType: markdownOnly
        label: Info Page Fragmented Files
        name: infopage
  theme:
    linkcolor:
      main: lightblue
      visited: lightslategrey
    background:
      color:
        type: lineargradient
        lightdarktheme: true
        light:
          left:
            color: "#0813fd"
            position: 24%
          right:
            color: "#2d8bfc"
            position: 69%
        dark:
          left:
            color: "#0810ba"
            position: 24%
          right:
            color: "#1e60af"
            position: 69%
        lineargradient:
          light:
            left:
              color: "#0813fd"
              position: 24%
            right:
              color: "#2d8bfc"
              position: 69%
          dark:
            left:
              position: 10%
            right:
              position: 50%
        lightdarkscheme: false
    font:
      family: BloggerSans, Roboto, Helvetica, Arial, sans-serif
      custom:
        - family: BloggerSans
          url: /fonts/Blogger_Sans.otf
    pagePreviewImage: /images/preview.png
    list:
      relatedArticle:
        enable: true
        articleSnippetStyle: listStyle
      sectionList:
        articleSnippetStyle: listStyle
    textColor:
      noDarkMode: true
    iconFonts:
      fontawesome:
        enable: true
        type: cdnjs
        kits:
          kitName: "0"
        cdnjs:
          version: 6.4.2
      bootstrapIcons:
        enable: false
        type: jsdeliver
  author: dplayzgames06
  relatedArticle:
    enable: true
    articleSnippetStyle: listStyle
  disableFeature:
    IEChecks: false
    googlePlatformSDK: false
    googleTranslate: false
    widgetbotcrate: false
    onesignalSDK: false
    fbSDK: false
    twitterSDK: false
  devBranchNotice:
    enable: true
    bugReportURL: https://github.com/dplayz/codenamecore
  comments:
    enable: true
    disqusShortName: dplayz-games
  fbSDKID: 2932203920349027
  pwa:
    customSplashImage: /images/splash.png
  description: The official website of dplayz Games where information about him are posted.
  identity:
    sdk:
      onesignalSDKID: c297670d-63a2-4232-8f52-a8602fdffc33
      fbSDKID: "2932203920349027"
    general:
      logo: /images/logo.png
      description: The official website of dplayz Games where information about him
        are posted.
      defaultAuthor:
        name: dplayzgames06
        gravatar: dp@dplayzgames06.tk
      pagePreviewImage: /images/preview.png
      favicon: favicon.ico
    webmaster:
      noIndexAll: false
    analytics:
      googleAnalytics:
        disablePageView: false
  psa:
    enable: true
    entries:
      - oneTime: true
        id: semi-feature-reference-notice-1
        content: >
          This site serves as a semi-feature reference of my theme. Expect
          constant changes. Participate also on the
          [development](https://github.com/dplayz/codenamecore) if you want
        buttonText: Alright
enableRobotsTXT: true
buildDrafts: false
markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
theme: codenamecore
module:
  mounts:
    - source: data
      target: data
    - source: readFile
      target: data
taxonomies:
  category: categories
  tag: tags
  authors: author
baseURL: https://dplayzgames06.tk
title: dplayz Games
enableGitInfo: true
menu:
  main:
    - identifier: Info
      name: Info
      params:
        url: /info
        iconClass: fa-solid fa-info-circle
      weight: 1
    - identifier: svcstats
      name: Status
      params:
        url: https://status.dplayzgames06.tk
        iconClass: fa-solid fa-angles-up
      weight: 2
    - name: Workstation
      identifier: workstationsvc
      weight: 3
      params:
        url: https:///workstation.dplayzgames06.tk
        iconClass: fa-solid fa-list-check
      parent: ""
    - identifier: projectshowcasesvc
      name: Projects(Soon)
      params:
        url: https://projects.dplayzgames06.tk
        iconClass: fa-solid fa-clipboard-list
      weight: 4
outputs:
  home:
    - HTML
    - RSS
    - CMSCONFIG
    - MANIFEST
