baseURL: 'https://dplayzgames06.tk/'
languageCode: en-us
title: dplayz Games
theme: codenamecore
params:
  description: The official website of dplayz Games where information about him are posted.
  pagePreviewImage: /images/preview.png
  author: dplayzgames06

  fbSDKID: 2932203920349027
  onesignalSDKID: c297670d-63a2-4232-8f52-a8602fdffc33

  devBranchNotice:
    enable: true
    bugReportURL: https://github.com/dplayz/codenamecore
  sectionList: 
    articleSnippetStyle: listStyle
  relatedArticle: 
    enable: true
    articleSnippetStyle: listStyle
  copyrightyearStarted: 2021 
  copyrightyearToday: 2022
  copyrightHolder: dplayz Games
  copyrightNotes: Elements of this website are owned by dplayz Games. Other third party copyrighted content are owned by their respective owners.
enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false
disqusShortName: dplayz-games

taxonomies:
  category : categories
  tag : tags

markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

timeZone: "Asia/Manila"
menu:
  main:
  - identifier: Info
    name: Info
    params: 
      url: /info
    weight: 1
  - identifier: blog
    name: Blog
    params: 
      url: /blog
    weight: 2
  - identifier: svcstats
    name: Status
    params: 
      url: https://status.dplayzgames06.tk
    weight: 3
  - identifier: workstationsvc
    name: Workstation
    params: 
      url: https://workstation.dplayzgames06.tk
    weight: 4
