baseURL: 'https://dplayzgames06.tk/'
languageCode: en-us
title: dplayz Games
theme: codenamecore
params:
  description: The official website of dplayz Games where information about him are posted.
  author: dplayzgames06
  theme:
    linkcolor: 
      main: "lightblue"
      visited: "lightslategrey"
    background:
      color:
        type: lineargradient
        lightdarkscheme: "true"
        light:
          left:
            color: "#0813fd"
            position: "24%"
          right:
            color: "#2d8bfc"
            position: "69%"
        dark:
          left:
            color: "#0810ba"
            position: "24%"
          right:
            color: "#1e60af"
            position: "69%"
    font:
      family: "BloggerSans, Roboto, Helvetica, Arial, sans-serif"
      custom:
        - family: BloggerSans
          url: "/fonts/Blogger_Sans.otf"
    pagePreviewImage: /images/preview.png
  comments:
    enable: true
    disqusShortName: dplayz-games
  fbSDKID: 2932203920349027
  onesignalSDKID: c297670d-63a2-4232-8f52-a8602fdffc33
  comments:
    enable: true
    disqusShortName: worldofsteelcraft
  devBranchNotice:
    enable: true
    bugReportURL: https://github.com/dplayz/codenamecore
  sectionList: 
    articleSnippetStyle: listStyle
  relatedArticle: 
    enable: true
    articleSnippetStyle: listStyle
  pwa:
    customSplashImage: "/images/splash.png"
  copyright:
    start: 2021
    today: 2022
    rightholder: "dplayz Games"
    notes: Elements of this website are owned by dplayz Games unless otherwise noted.
enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false

taxonomies:
  category : categories
  tag : tags

markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

timeZone: "Asia/Manila"
menu:
  main:
  - identifier: Info
    name: Info
    params: 
      url: /info
    weight: 1
  - identifier: svcstats
    name: Status
    params: 
      url: https://status.dplayzgames06.tk
    weight: 2
  - identifier: workstationsvc
    name: Workstation
    params: 
      url: https://workstation.dplayzgames06.tk
    weight: 3

outputs:
  home:
    - HTML
    - RSS
    - MANIFEST

module:
  mounts:
  - source: data
    target: data
  - source: readFile
    target: data